### ISSUE TITLE
Unable to explain

### ISSUE THREAD

**Issue by arjunkharbanda** [tomlau10/gcc-make-run#11]
the current target is syswow64 make it `system32 as i am used to that after using sublime text3 also including the build that I used in Sublime text may come handy. and thanks for making this package in the  first place will love to help but I don't have any knowledge regarding CSON/JSON
[C.txt](https://github.com/tomlau10/gcc-make-run/files/423563/C.txt)
[C++.txt](https://github.com/tomlau10/gcc-make-run/files/423562/C.txt)

**Comment by tomlau10** [comment]
to build a `32bit` target, you shall include `-m32` in the compiler flags.
hope this can solve your problem and you may close this issue afterwards or ask for further help.
and thanks for using this package. :smile:

**Comment by arjunkharbanda** [comment]
Thanks

**Comment by arjunkharbanda** [comment]
not helpfull

**Comment by arjunkharbanda** [comment]
![screenshot 8](https://cloud.githubusercontent.com/assets/15190745/17762199/eea29830-652b-11e6-9cd7-e66e21ab8774.png)

![screenshot 9](https://cloud.githubusercontent.com/assets/15190745/17762211/03b0ec0e-652c-11e6-8d1c-7206a6c8f8fa.png)
see this on Atom when I compile it is showing that datbase icon and on the other hand in ST3 it cmd in admin. please help make  as same in Atom as I am so use to it.

**Comment by tomlau10** [comment]
sorry I don't quite get the issue
you mean that the `cmd` that this plugin invokes is shown as the `database icon` instead of a normal `cmd icon`?!
i never come into this :fearful: can you provide more information?
for example when right click on that `database icon cmd`, see what actual process and path is that executable?

and maybe my previous reply got your issue wrongly
what is the original issue `build target` you mentioned about?
by `syswow64` and `system32` do you mean `32bit 64bit build target` ?

**Comment by arjunkharbanda** [comment]
![capture](https://cloud.githubusercontent.com/assets/15190745/17776184/08c1a588-6579-11e6-8f66-3ffb9739b858.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15190745/17776183/08bb334c-6579-11e6-9d13-d01b5d6e67a1.PNG)
sorry to confuse you but this is actual issue and here the info you want and `syswow64` and `system32` are target locations

**Comment by tomlau10** [comment]
to spawn a shell, my plugin just invoke `start cmd /c "command to run"`

from your first figure, the comment `Shortcut To C:\Windows\SysWOW64\cmd.exe` seems to me that it somehow `hides` the original `cmd` command and invoke the `StartDB.bat` instead ...

perhaps your `PATH` environment variable priority has some problem
please type `where cmd` in a normal command window then show the output here?

**Comment by arjunkharbanda** [comment]
![capture](https://cloud.githubusercontent.com/assets/15190745/17811648/48d52f82-6641-11e6-95fc-20cb75caba55.PNG)
here you go

**Comment by tomlau10** [comment]
output seems normal...
how about `where cmd` at your source files' path ?

does only that source file will invoke the `StartDB.bat` or other source files at different paths also have the same issue?

**Comment by tomlau10** [comment]
ahh... in your first figure the `Start Database Properties`, press the `general` tab and see where is the location of that shortcut?

i think maybe deleting that shortcut will help (click `Shortcut` tab and press `Open file location` will take you there)
back it up first though :sweat_smile:

**Comment by arjunkharbanda** [comment]
![screenshot 10](https://cloud.githubusercontent.com/assets/15190745/17815930/24ba6320-6654-11e6-92c7-f8d3c0e78cf0.png)
So I uninstall Oracle DatabaseXE and this is what this is what happen looks like problem solved but here is catch
![capture](https://cloud.githubusercontent.com/assets/15190745/17816017/9d325d62-6654-11e6-8b8e-ee2867c348e3.PNG)
The target is still  `sysWOW64` `C:/Windows/SysWOW64/` to be more accurate and I have to reinstall Oracle Database XE as I am student and it is part of my course so I guess I have to use it like this even if I don't like this
lastly I want to help you in this please let me know  how to start with JSON/CSON and also do  you want me to close this issue

**Comment by tomlau10** [comment]
For a 64bit windows, `sysWOW64` actually means the 32bit version and `system32` means the 64bit version, see [this link](https://en.wikipedia.org/wiki/WoW64)

so `C:\Windows\SysWOW64\cmd.exe` is the 32 bit version `cmd` and i don't think it will cause problem when executing the built executable. i also realized in my case, the plugin also invokes the `sysWOW64 cmd`. Does it cause problems when using anyway in your case?

for learning, I strongly recommend starting with [Learn X in Y minutes](https://learnxinyminutes.com/)
This is an excellent site providing a good start for many languages and it contains further readings as well

I think this issue is not related to the usage or bug in this plugin so I will close it for now. Be sure to open new issue if you have new problems :smile:
