### ISSUE TITLE
xterm doesn't open

### ISSUE THREAD

**Issue by alefpereira** [tomlau10/gcc-make-run#13]
The part `read -n1 -p 'Press any key to continue...'` was not working here. I changed only to `read` and xterm opened. `echo -n 'Press any key to continue...'; read` also works and has the expected effect.

Also, I'd like to suggest the terminal setting as an option in the package settings on Atom, that because it would make more customizable for people that use terminator, for instance, or in case of change the behaviour to keep the console open by adding a `bash` or `zsh` at the end, as these users have to edit directly in the code to get these features. Thank you!

**Comment by tomlau10** [comment]
thanks for your suggestion 😄 

---
i am a Windows user,
in order to support cross platform, initially just added `xterm` for ubuntu and `Terminal` for macOS

and it seems very difficult to make `terminal setting as an option in the package settings` as different platform or terminal need a whole set of different command to `compile run` or `make run` 🤔
