### ISSUE TITLE
some terrible error

### ISSUE THREAD

**Issue by ToSeven** [tomlau10/gcc-make-run#14]
my computer system is window10 
the compiler is tdm-gcc 
![default](https://cloud.githubusercontent.com/assets/14891443/21580499/e51b5570-d035-11e6-978c-5d1813a62f65.PNG)

**Comment by tomlau10** [comment]
you need full path to `executable` instead of the `directory`
eg: `F:\Program Files (x86)\tdm-gcc\bin\gcc.exe`

---
if you set the `directory` in you `$PATH` environment variable, then you can leave these config as default
you may follow [this youtube video](https://www.youtube.com/watch?v=C-U9SGaNbwY)

---
if the above resolve your issue, you may close it
hope this help :smiley:

**Comment by ToSeven** [comment]
thanks you very much. but there is another error
![default](https://cloud.githubusercontent.com/assets/14891443/21580571/90f04928-d03b-11e6-8d5e-a776a47d4075.PNG)

**Comment by tomlau10** [comment]
`missing separator` seems will only occur when running makefiles
- did you used `run makefile` instead of just `compile run` ?
- or you specified `make` instead of `gcc` in the setting page for a gcc executable?
- can you take a screenshot of your final setting for me to see?

**Comment by ToSeven** [comment]
It is normal when I use compile run  but run makefile not 
my final setting 
![default](https://cloud.githubusercontent.com/assets/14891443/21585557/b93647b2-d0fd-11e6-8485-062ba98acecc.PNG)

**Comment by tomlau10** [comment]
your settings seems correct
and from your screenshot yesterday, it seems the plugin tried to `Make Run` on the `temp.c`
did you right click `temp.c` and `Make Run` instead of right clicking the `makefile` to do so?

---
the `Make Run` is really designed for `makefile` only
it can be invoked in 2 ways:
1. open the `makefile` as a tab in atom, in this tab, press `f6` (the default hotkey) then it will execute the makefile
2. right click the `makefile` on tree view then select `Make Run`

![image](https://cloud.githubusercontent.com/assets/16996876/21586185/dc697a82-d108-11e6-85a5-c7166ea15075.png)

**Comment by ToSeven** [comment]
thank you very much .I got it .you are so kindhearted
