### ISSUE TITLE
Compiler Selection

### ISSUE THREAD

**Issue by werling** [tomlau10/gcc-make-run#39]
Create Plug-in! But there is one small issue:
I'd like to choose a different compiler, but the program always compiles with default c++ and gcc. What im doing wrong? Also adding the compiler variables CXX and CC has no impact.

/Edit: Ok it only doesn't work if I select a Makefile. There it always uses the default compiler.

**Comment by werling** [comment]
Ok I see the problem. The library I'd like to compile uses in the Makefile the variables CXX and CC for the compiler selection. Is there a way in gcc-make-run to add make flags? I don't see it in the settings.
There is a variable in the code, but it only can be set to -B if unconditional build is activated. 
```
    mkFlags = if @shouldUncondBuild() then '-B' else ''

    # make
cmd = "\"#{mk}\" #{mkFlags} -f \"#{info.base}\""
```

**Comment by werling** [comment]
Ok I changed it by myself. I also added a checkbox to disable automatic execution of the build.
I can provide the changed file, if somebody is interested. Its especially useful for cross building
![image](https://user-images.githubusercontent.com/22643656/36950481-b8128da2-1ff6-11e8-9d70-6cbc81ba4a5f.png)

**Comment by tomlau10** [comment]
It's a bit late, but I don't quite understand your issue.

In the setting page there is two options namely **gcc Compiler** and **g++ Compiler** where you can choose another compiler.

Also I don't think **disable automatic execution of the build** matches the idea of this extension because it aims to compile/make **and run**, not just compile. 😂
