### ISSUE TITLE
Is there no 'Make Run' Atom command?

### ISSUE THREAD

**Issue by sergerold** [tomlau10/gcc-make-run#50]
I'd like tie Make Run to a button on my toolbar but I couldn't see any such command when using command palette.

**Comment by tomlau10** [comment]
I know it's a bit late. As I remember the `Make Run` feature is for specifying the `Makefile` to be run on the file tree view, because it needs to know which file to be triggered with. And if you already opened a Makefile tab, you can just use the `Compile Run` (default shortcut is `F6`) on that tab, and it will detect the file type is a `Makefile` and use `make -f` to execute it.
